Container: container_1761119194299_0029_01_000001 on vm-99230800_40415
LogAggregationType: AGGREGATED
======================================================================
LogType:stdout-active
LogLastModifiedTime:Wed Oct 22 09:06:14 +0000 2025
LogLength:3001
LogContents:
2025-10-22 09:06:14,014 INFO UserConsole [redirect output]: 2025-10-22 09:06:14 | INFO: Arguments instantiated: {'run_id': 'fc9010ce-2943-485c-adfc-a7fbe30569fc', 'key_vault_name': 'MetEdwKeyVaultProd', 'key_vault_linked_service_name': 'MET_EDW_KeyVault', 'sql_password_secret_name': 'ProcfwkSqlDbPassword', 'sql_host_name': 'bdaprodsql.public.35133d2c7131.database.windows.net', 'sql_port': '3342', 'sql_database': 'S_procfrwk', 'sql_user': 'procfwk-user', 'source_data_source': ['domain_inventory'], 'target_data_source': 'fact_spark_database', 'load_definitions': ['fact_cycle_count_schedule', 'fact_cycle_count_transaction', 'fact_transfer_order_receipt', 'fact_transfer_orders', 'fact_transfer_order_shipment'], 'restart': None, 'sequential': None}

2025-10-22 09:06:14,197 INFO UserConsole [redirect output]: Traceback (most recent call last):
  File "/mnt/var/hadoop/tmp/nm-local-dir/usercache/trusted-service-user/appcache/application_1761119194299_0029/container_1761119194299_0029_01_000001/main.py", line 302, in <module>

2025-10-22 09:06:14,205 INFO UserConsole [redirect output]:     from spark_helpers import functions as func
  File "spark_helpers.zip/spark_helpers/functions.py", line 12, in <module>
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 59, in <module>
    from ._download import StorageStreamDownloader
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/azure/storage/blob/_download.py", line 20, in <module>
    from ._encryption import (
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/azure/storage/blob/_encryption.py", line 21, in <module>
    from cryptography.hazmat.primitives.ciphers import Cipher
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 11, in <module>
    from cryptogr
2025-10-22 09:06:14,205 INFO UserConsole [redirect output]: aphy.hazmat.primitives.ciphers.base import (
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 10, in <module>
    from cryptography.exceptions import (
  File "/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: /home/trusted-service-user/cluster-env/env/lib/python3.10/lib-dynload/../../libcrypto.so.3: version `OPENSSL_3.3.0' not found (required by /home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/cryptography/hazmat/bindings/../../../../../libssl.so.3)

2025-10-22 09:06:14,331 INFO UserConsole [pool-41-thread-1]: Calling LA appender v2 Stop...


End of LogType:stdout-active
******************************************************************************

